[tools]
"github:extsoft/prosefmt" = "v2026.4.10"
go = "1.25.6"
hk = "1.40.0"
pkl = "0.30.2"
shellcheck = "0.10.0"
shfmt = "3.11.0"

[env]
MISE_EXPERIMENTAL = "false"
DIST_DIR = "dist"

[tasks.check]
description = "check the project files"
run = "hk check"

[tasks.fix]
description = "fix the project files"
run = "hk fix"
